load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "my_op.so",
    srcs = ["my_op.cc"],
)

tf_custom_op_library(
    name = "zero_out.so",
    srcs = ["zero_out.cc"],
)
